#pragma once

// Stub version.h - actual version is generated by CMake
// Do not edit this file - it is auto-generated
// This file is used when CMake hasn't generated the version.h yet

#include <cstdint>
#include <string_view>

#define GE_VERSION_MAJOR 0
#define GE_VERSION_MINOR 1
#define GE_VERSION_PATCH 0
#define GE_VERSION_STRING "0.1.0"
#define GE_BUILD_TYPE "Debug"
#define GE_BUILD_DATE "Unknown"
#define GE_PLATFORM_NAME "Unknown"

#include <string_view>

namespace ge {

struct Version {
    static constexpr int Major = 0;
    static constexpr int Minor = 1;
    static constexpr int Patch = 0;
    static constexpr std::string_view String = "0.1.0";
    static constexpr std::string_view BuildType = "Debug";
    static constexpr std::string_view BuildDate = "Unknown";
    static constexpr std::string_view Platform = "Unknown";
};

} // namespace ge